### ISSUE TITLE
flask.ext was deprecated

### ISSUE THREAD

**Issue by nad2000** [mgood/flask-debugtoolbar#101]
"flask.ext"  (https://github.com/pallets/flask/issues/1135) has been deprecated a while ago. FdT keeps importing *flask_sqlalchemy* with flask.ext resulting in warning messages:

`exthook.py:71: ExtDeprecationWarning: Importing flask.ext.sqlalchemy is deprecated, use flask_sqlalchemy instead`

**Comment by caimaoy** [comment]
How to fixed the warming?

**Comment by lingthio** [comment]
Instead of using::

    from flask.ext.sqlalchemy import ...

Use::

    from flask_sqlalchemy import ...

**Comment by caimaoy** [comment]
Thanks

**Comment by jeffwidman** [comment]
Dupe of #94
