### ISSUE TITLE
ExtDeprecationWarning: Importing flask.ext.sqlalchemy is deprecated, use flask_sqlalchemy instead.

### ISSUE THREAD

**Issue by syzygykr** [mgood/flask-debugtoolbar#103]
/flask_debugtoolbar/panels/sqlalchemy.py contains a deprecated import call. Not particularly problematic, but it the amount of work required to fix it is minimal.

**Comment by jeffwidman** [comment]
this has been fixed in master, just none of the maintainers have had time to cut a new release yet.
