### ISSUE TITLE
New Release for pip?

### ISSUE THREAD

**Issue by rlam3** [mgood/flask-debugtoolbar#104]
New Release for pip? I'm getting the import error from sqlalchemy ExtDeprecationWarning: Importing flask.ext.sqlalchemy. I'm on version 0.10. Thanks!

**Comment by askz** [comment]
Please could someone wake up?

**Comment by rlam3** [comment]
Any updates @mgood? Would love to hear your thoughts or possibly have somebody else take over in maintaining this repo. Thanks!

**Comment by askz** [comment]
+1 Really think we shouldn't abandon this repo like this.

**Comment by dsully** [comment]
+1 @mgood - can you make a release? This will also fix warnings about flask.ext

**Comment by jeffwidman** [comment]
Spent some time cleaning up stuff this evening. I'll try to get a new version out tomorrow on Pypi.

**Comment by rlam3** [comment]
Thank you! :)

**Comment by jeffwidman** [comment]
It'll have to be this weekend, I didn't get to it today.

**Comment by jeffwidman** [comment]
Just pushed `0.10.1` to Pypi

**Comment by askz** [comment]
wow thanks
