### ISSUE TITLE
tojson filter error when upgrading to Jinja2.9

### ISSUE THREAD

**Issue by vindarel** [mgood/flask-debugtoolbar#111]
Hi,
I encountered an error with the debug toolbar when I tried upgrading Jinja to the newest 2.9. 

The following pb with the `tojson` filter is a debug-toolbar bug to me because it doesn't occur when I disable it.

> var require = {{ app.extensions['webassets'].requirejs_config | tojson }};
> TypeError: do_tojson() takes at least 2 arguments (1 given)

I wonder how the debug toolbar would influence this, but that's my observation. Does that ring a bell ?

I'm on flask-debugtoolbar 0.10.1 and Flask 0.12.

Thanks.

**Comment by jeffwidman** [comment]
Afraid I cannot reproduce. On the surface, this looks like a webassets bug, not a debugtoolbar bug. Can you try again with the latest versions of flask-debugtoolbar, flask, and jinja and see if it's still happening?
