### ISSUE TITLE
Usage of deprecated function `Request.is_xhr`

### ISSUE THREAD

**Issue by Bryan21B** [mgood/flask-debugtoolbar#131]
When using py.test a deprecation warning is shown for Flask-DebugToolbar: 

`lib/python3.7/site-packages/flask_debugtoolbar/__init__.py:190: DeprecationWarning: Request.is_xhr is deprecated. Given that the X-Requested-With header is not a part of any spec, it is not reliable
    if response.status_code in self._redirect_codes and not real_request.is_xhr:`

It looks like it's linked to jsonify: https://github.com/pallets/flask/issues/2549

**Comment by jeffwidman** [comment]
Thanks! Fixed in https://github.com/mgood/flask-debugtoolbar/commit/7ce099c3d092cf0dcb106260396a86ba75627560.
