### ISSUE TITLE
project status still active?

### ISSUE THREAD

**Issue by zachvalenta** [mgood/flask-debugtoolbar#140]
Based on recent issues/PRs closed, the project looks inactive. Status update [along these lines](https://github.com/noirbizarre/flask-restplus/issues/612) would be nice.

**Comment by djnorrisdev** [comment]
This isn't a good sign.

**Comment by mattaw** [comment]
I just emailed @jeffwidman encouragement, as he committed something in Dec 2019. I have just submitted a minor pull request and there are about 20 or so out there of which many are simple one-liners that could help. Heck, some even improve the documentation!!?!

**Comment by jeffwidman** [comment]
I never really got going with this project, but I'll try to be a it more active. 

I fixed some of the outstanding issues:
https://github.com/mgood/flask-debugtoolbar/commits/master
