### ISSUE TITLE
SQLAlchemy  0 queries even for Flask-SQLAlchemy

### ISSUE THREAD

**Issue by ducu** [mgood/flask-debugtoolbar#78]
Anyone else experiencing this?
Meanwhile I'll stick to `SQLALCHEMY_ECHO = True`, too bad, the toolbar is looking good and all other panels are working but I'm only interested in the queries.

**Comment by mgood** [comment]
Are you running the app in "debug" mode? (You can look for DEBUG in the Config panel.)

Flask-SQLAlchemy captures queries in debug mode by default, but if that is false, you'll need to also set the `SQLALCHEMY_RECORD_QUERIES = True` in your config. See: http://flask-sqlalchemy.pocoo.org/2.0/api/#flask.ext.sqlalchemy.get_debug_queries

I know that's not obvious, so I'm working on a patch that will display better help in the SQLAlchemy panel if it notices common problems that would prevent capturing the SQL queries.

If `DEBUG` or `SQLALCHEMY_RECORD_QUERIES` are true, then maybe this is a different issue, and I'd need a little more info to help debug.

**Comment by mgood** [comment]
I've pushed an update 61d1fc26786511c5142c55e5ccacfafe21cc666e that will detect common setup issues with Flask-SQLAlchemy and display steps to fix the query recording. I'm assuming you're just missing the `SQLALCHEMY_RECORD_QUERIES`, which this update will detect.

If you have another issue please reopen with more details.

**Comment by ducu** [comment]
Sorry but it doesn't work.. What info would you need to debug this?

![screen shot 2015-04-18 at 15 46 39](https://cloud.githubusercontent.com/assets/104093/7215469/5af114f0-e5e2-11e4-894c-788577aa0b0b.png)

**Comment by iambibhas** [comment]
Facing the same issue. SQLAlchemy - 0 queries. DEBUG is True.
