### ISSUE TITLE
Deprecated import from flask.ext.sqlalchemy

### ISSUE THREAD

**Issue by mlenzen** [mgood/flask-debugtoolbar#93]
This import is throwing a deprecation warning with Flask 0.11

    flask_debugtoolbar/panels/sqlalchemy.py:2:    from flask.ext.sqlalchemy import get_debug_queries, SQLAlchemy

**Comment by edouardberthe** [comment]
And your PR : https://github.com/mgood/flask-debugtoolbar/pull/94

**Comment by homeworkprod** [comment]
Jup, that warning is annoying (I see it twice on startup).

**Comment by jeffwidman** [comment]
Fixed in #93 and #97

**Comment by mrasband** [comment]
Can you make a release with this change, or is there a milestone planned for it?  Thank you!

**Comment by jeffwidman** [comment]
Fix is now live on Pypi under 0.10.1
