### ISSUE TITLE
Adding @jeffwidman as collaborator on Pypi

### ISSUE THREAD

**Issue by jeffwidman** [mgood/flask-debugtoolbar#98]
@mgood Can you add me as a collaborator on Pypi and I can cut a new release?

Be nice to get the fix for #93 out the door

**Comment by mgood** [comment]
Assuming you go by `jeffwidman` on PyPI, you should have access now. Thanks for taking this on.

**Comment by jeffwidman** [comment]
Yep, thanks! That was fast turnaround, afraid that I may not get to this until the weekend

**Comment by bastula** [comment]
Any idea when a new release will be made?

Cheers on the usefulness of this project!
